"use client"

import React from 'react'
import { Button } from '../ui/button';
import { Download } from 'lucide-react';


const DownloadSummaryButton = ({ title, summaryText, fileName, createdAt }: {
    title: string;
    summaryText: string;
    fileName: string;
    createdAt: string;
}) => {

    const handleDownload = () => {
        const summaryContent = `# ${title} 
        Generated Summary 
        Generated on:${new Date(createdAt).toLocaleDateString()} ${summaryText}
        Original File :${fileName}
        Generated by Sommaire
        `

        // Create a Blob with the content
        const blob = new Blob([summaryContent], { type: 'text/plain' });

        // Create a download link
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;  // Use title as filename or default to 'summary.txt'

        // Trigger the download
        document.body.appendChild(link);
        link.click();

        // Clean up
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return (
        <Button size={"sm"} className='h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50 ' onClick={handleDownload} >
            <Download className='h-4 w-4 mr-1' />
        </Button>
    )
}

export default DownloadSummaryButton